### ISSUE TITLE
Adding Policies to a bare token seems to bomb

### ISSUE THREAD

**Issue by omada-jacob-smith** [jsundh/ansible-modules-consul-acl#1]
Hi,

Recently I was trying to make a token with a given accessor id so that I could continual update only the same token (I tried to use the match_description, but it seemed to create new tokens too readily). So I generate the new token with some arbitary accessor like so:
```
- name: Generate agent accessor_id
  uri:
    url: "https://consul.foo.bar/v1/acl/token"
    headers:
      X-Consul-Token: "blahblah"
    method: PUT
    body_format: json
    body:
      Description: "Agent token"
      AccessorID: "$(uuidgen)"
  register: accessor_id
  failed_when: "accessor_id.status != 200 and 'AccessorID is already in use' not in accessor_id.content"
```

Note: the consul_acl_token module does not seem to handle all uppercase tokens particularly well.

Then I do:
```
- name: Configure agent token
  consul_acl_token:
    accessor_id: "accessor id from above"
    url: "https://consul.foo.bar"
    token: "blahblah"
    policies:
      - name: agent
    state: present
```
And unless the first task adds a policy, it will fail.
